spring.application.name=desafiotenpo
server.port=8081
external.service.max-retries=3

# Redis Cache
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.cacheTimeInMin=30

management.endpoints.web.exposure.include=health

spring.main.allow-bean-definition-overriding=true
logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.data.redis=DEBUG

# R2DBC connection settings
spring.r2dbc.url=r2dbc:postgresql://postgres:postgres@localhost:5432/mydb
spring.r2dbc.username=tenpo
spring.r2dbc.password=tenpo

# Rate limiter config
# Max requests per minute
rate-limiter.limit=3
rate-limiter.window=1m

# Webclient config
webclient.serviceCallMaxRetries=3
webclient.timeoutInMs=1000




